[package]
name = "containerdebug"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }

hickory-resolver = "0.24.1"
local-ip-address = "0.6.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs", version = "0.81.0" }
sysinfo = "0.32.0"
tracing = "0.1.40"
users = "0.11.0"

[build-dependencies]
built = { version = "0.7", features = ["chrono", "git2"] }
