[package]
name = "containerdebug"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

hickory-resolver = "0.24"
local-ip-address = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.8"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs", tag = "stackable-operator-0.93.1" }
sysinfo = { version = "0.33", features = ["serde"] }
tracing = "0.1"

[build-dependencies]
built = { version = "0.8", features = ["chrono", "git2"] }
