[package]
name = "containerdebug"
version = "0.1.0"
edition = "2021"

[dependencies]

hickory-resolver = "0.24.1"
local-ip-address = "0.6.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sysinfo = "0.32.0"
users = "0.11.0"
