---
name: pre-commit

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.85.0"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: stackabletech/actions/run-pre-commit@9aae2d1c14239021bfa33c041010f6fb7adec815 # v0.8.2
        with:
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
          # rust-src is required for trybuild stderr output comparison to work
          # for our cases.
          # See: https://github.com/dtolnay/trybuild/issues/236#issuecomment-1620950759
          rust-components: rustfmt,clippy,rust-src
